"""Lazy export mapping and module availability detection for PEP 562 front door.

Extracted from ``__init__.py`` to keep the top-level package within the line
limits prescribed by ADR-0002.
"""

from __future__ import annotations


def module_installed(name: str) -> bool:
    """Check if a module is installed without importing it."""
    from importlib.util import find_spec

    try:
        return find_spec(name) is not None
    except (ImportError, ValueError):  # pragma: no cover - malformed install
        return False


AIOSQLITE_AVAILABLE_FOR_ALL = module_installed("aiosqlite")

# name -> module path providing it.
LAZY_EXPORTS: dict[str, str] = {
    "AggregateId": "eventsource.domain.types",
    "EventId": "eventsource.domain.types",
    "TenantId": "eventsource.domain.types",
    "CorrelationId": "eventsource.domain.types",
    "CausationId": "eventsource.domain.types",
    "create_async_engine": "eventsource.adapters._sql.engine",
    "DomainEvent": "eventsource.domain.event",
    "DomainCommand": "eventsource.domain.command",
    "EventRegistry": "eventsource.domain.event_registry",
    "default_registry": "eventsource.domain.event_registry",
    "register_event": "eventsource.domain.event_registry",
    "get_event_class": "eventsource.domain.event_registry",
    "get_event_class_or_none": "eventsource.domain.event_registry",
    "is_event_registered": "eventsource.domain.event_registry",
    "list_registered_events": "eventsource.domain.event_registry",
    "EventTypeNotFoundError": "eventsource.domain.exceptions",
    "DuplicateEventTypeError": "eventsource.domain.exceptions",
    "InMemoryEventStore": "eventsource.adapters.memory",
    "PostgreSQLEventStore": "eventsource.adapters.postgresql",
    "ASYNCPG_AVAILABLE": "eventsource.adapters.postgresql",
    "AggregateRoot": "eventsource.domain.aggregate",
    "AggregateRepository": "eventsource.application.aggregates.repository",
    "DeclarativeAggregate": "eventsource.domain.aggregate",
    "DeciderAggregate": "eventsource.domain.decider",
    "handles": "eventsource.domain.decorators",
    "EventBus": "eventsource.ports",
    "BaseEventBus": "eventsource.adapters._bus.base",
    "EventHandlerFunc": "eventsource.ports",
    "AsyncEventHandler": "eventsource.ports.handlers",
    "InMemoryEventBus": "eventsource.adapters.memory.bus",
    "SubscriptionRegistry": "eventsource.adapters._bus.registry",
    "RetryPolicy": "eventsource.adapters._bus.retry",
    "RecordingEventBus": "eventsource.testing.recording",
    "EventHandler": "eventsource.ports.handlers",
    "SyncEventHandler": "eventsource.ports.handlers",
    "FlexibleEventHandler": "eventsource.ports.handlers",
    "EventSubscriber": "eventsource.ports.handlers",
    "FlexibleEventSubscriber": "eventsource.ports.handlers",
    "RedisEventBus": "eventsource.adapters.redis",
    "RedisEventBusConfig": "eventsource.adapters.redis",
    "RedisEventBusStats": "eventsource.adapters.redis",
    "RedisNotAvailableError": "eventsource.adapters.redis",
    "REDIS_AVAILABLE": "eventsource.adapters.redis",
    "RabbitMQEventBus": "eventsource.adapters.rabbitmq",
    "RabbitMQEventBusConfig": "eventsource.adapters.rabbitmq",
    "RabbitMQEventBusStats": "eventsource.adapters.rabbitmq",
    "RabbitMQNotAvailableError": "eventsource.adapters.rabbitmq",
    "RABBITMQ_AVAILABLE": "eventsource.adapters.rabbitmq",
    "KafkaEventBus": "eventsource.adapters.kafka",
    "KafkaEventBusConfig": "eventsource.adapters.kafka",
    "KafkaEventBusStats": "eventsource.adapters.kafka",
    "KafkaNotAvailableError": "eventsource.adapters.kafka",
    "KAFKA_AVAILABLE": "eventsource.adapters.kafka",
    "AggregateNotCreatedError": "eventsource.domain.exceptions",
    "AggregateNotFoundError": "eventsource.domain.exceptions",
    "CommandRejectedError": "eventsource.domain.exceptions",
    "EventNotFoundError": "eventsource.domain.exceptions",
    "EventSourceError": "eventsource.domain.exceptions",
    "EventVersionError": "eventsource.domain.exceptions",
    "HandlerDispatchError": "eventsource.domain.exceptions",
    "OptimisticLockError": "eventsource.domain.exceptions",
    "ProjectionError": "eventsource.domain.exceptions",
    "CheckpointRepository": "eventsource.ports.checkpoints",
    "SQLCheckpointRepository": "eventsource.adapters.sql",
    "InMemoryCheckpointRepository": "eventsource.adapters.memory",
    "CheckpointData": "eventsource.ports.checkpoints",
    "LagMetrics": "eventsource.ports.checkpoints",
    "DLQRepository": "eventsource.ports.dlq",
    "SQLDLQRepository": "eventsource.adapters.sql",
    "InMemoryDLQRepository": "eventsource.adapters.memory",
    "DLQEntry": "eventsource.ports.dlq",
    "DLQStats": "eventsource.ports.dlq",
    "ProjectionFailureCount": "eventsource.ports.dlq",
    "OutboxRepository": "eventsource.ports",
    "PostgreSQLOutboxRepository": "eventsource.adapters.postgresql",
    "InMemoryOutboxRepository": "eventsource.adapters.memory",
    "OutboxEntry": "eventsource.ports",
    "OutboxStats": "eventsource.ports",
    "outbox_event_data": "eventsource.ports",
    "EventSourceJSONEncoder": "eventsource.adapters.serialization",
    "Projection": "eventsource.application.projections.base",
    "CheckpointTrackingProjection": "eventsource.application.projections.base",
    "DeclarativeProjection": "eventsource.application.projections.base",
    "replay": "eventsource.application.projections.replay",
    "ReplayFailure": "eventsource.application.projections.replay",
    "ReplayReport": "eventsource.application.projections.replay",
    "ReplayFailedError": "eventsource.application.projections.replay",
    "StoreProjection": "eventsource.application.projections.store",
    "ProjectionOptions": "eventsource.application.projections.store",
    "DatabaseProjection": "eventsource.adapters.sql.projection",
    "ReadModelProjection": "eventsource.adapters.sql.readmodel_projection",
    "ReadModel": "eventsource.ports.readmodels",
    "AggregateTypeNotSetError": "eventsource.domain.exceptions",
    "AggregateTypeMismatchError": "eventsource.domain.exceptions",
    "AggregateIdMismatchError": "eventsource.domain.exceptions",
    "Snapshot": "eventsource.ports.snapshots",
    "SnapshotStore": "eventsource.ports.snapshots",
    "InMemorySnapshotStore": "eventsource.adapters.memory.snapshots",
    "SnapshotError": "eventsource.domain.exceptions",
    "SnapshotDeserializationError": "eventsource.domain.exceptions",
    "SnapshotSchemaVersionError": "eventsource.domain.exceptions",
    "SnapshotNotFoundError": "eventsource.domain.exceptions",
    "SyncEventStoreAdapter": "eventsource.adapters.sync",
    "tenant_context": "eventsource.domain.tenant_context",
    "TenantContextToken": "eventsource.domain.tenant_context",
    "get_current_tenant": "eventsource.domain.tenant_context",
    "get_required_tenant": "eventsource.domain.tenant_context",
    "set_current_tenant": "eventsource.domain.tenant_context",
    "reset_tenant_context": "eventsource.domain.tenant_context",
    "clear_tenant_context": "eventsource.domain.tenant_context",
    "tenant_scope": "eventsource.domain.tenant_context",
    "tenant_scope_sync": "eventsource.domain.tenant_context",
    "TenantDomainEvent": "eventsource.domain.tenant_events",
    "TenantContextNotSetError": "eventsource.domain.exceptions",
    "TenantContextResetError": "eventsource.domain.exceptions",
    "TenantMismatchError": "eventsource.domain.exceptions",
    "StreamId": "eventsource.domain",
    "Position": "eventsource.ports",
    "EventEnvelope": "eventsource.ports",
    "EventPublisher": "eventsource.ports",
    "AppendResult": "eventsource.ports",
    "ExpectedVersion": "eventsource.ports",
    "ReadDirection": "eventsource.ports",
    "StreamReadOptions": "eventsource.ports",
    "FeedReadOptions": "eventsource.ports",
    "CategoryReadOptions": "eventsource.ports",
    "AggregateStore": "eventsource.ports",
    "EventAppender": "eventsource.ports",
    "StreamReader": "eventsource.ports",
    "EventLookup": "eventsource.ports",
    "GlobalEventFeed": "eventsource.ports",
    "CategoryQuery": "eventsource.ports",
    "FullEventStore": "eventsource.ports",
    "collect": "eventsource.ports",
    "IntPositionCodec": "eventsource.adapters._sql.positions",
    "DuplicateEventError": "eventsource.domain.exceptions",
    "PositionDecodeError": "eventsource.ports.exceptions",
    "PositionForeignError": "eventsource.ports.exceptions",
    "AIOSQLITE_AVAILABLE": "eventsource.adapters.sqlite",
    "SQLiteEventStore": "eventsource.adapters.sqlite",
    "SQLiteOutboxRepository": "eventsource.adapters.sqlite",
}
