"""Entities ring. Pure: stdlib + pydantic only."""

from eventsource.domain.aggregate import AggregateRoot, DeclarativeAggregate
from eventsource.domain.command import DomainCommand
from eventsource.domain.decider import DeciderAggregate
from eventsource.domain.event import DomainEvent
from eventsource.domain.event_registry import (
    EventRegistry,
    default_registry,
    get_event_class,
    get_event_class_or_none,
    is_event_registered,
    list_registered_events,
    register_event,
)
from eventsource.domain.exceptions import (
    AggregateNotCreatedError,
    AggregateNotFoundError,
    AggregateTypeNotSetError,
    CommandRejectedError,
    DuplicateEventError,
    DuplicateEventTypeError,
    DuplicateHandlerError,
    EventBusError,
    EventNotFoundError,
    EventSourceError,
    EventStoreError,
    EventTypeNotFoundError,
    EventVersionError,
    HandlerDispatchError,
    HandlerSignatureError,
    OptimisticLockError,
    ProjectionError,
    SerializationError,
    SnapshotDeserializationError,
    SnapshotError,
    SnapshotNotFoundError,
    SnapshotSchemaVersionError,
    TenantContextNotSetError,
    TenantContextResetError,
    TenantMismatchError,
    UnhandledEventError,
)
from eventsource.domain.stream_id import CATEGORY_PATTERN, StreamId
from eventsource.domain.types import (
    AggregateId,
    CausationId,
    CorrelationId,
    EventId,
    TenantId,
)

__all__ = [
    "CATEGORY_PATTERN",
    "AggregateId",
    "AggregateNotCreatedError",
    "AggregateNotFoundError",
    "AggregateRoot",
    "AggregateTypeNotSetError",
    "CausationId",
    "CommandRejectedError",
    "CorrelationId",
    "DeciderAggregate",
    "DeclarativeAggregate",
    "DomainCommand",
    "DomainEvent",
    "DuplicateEventError",
    "DuplicateEventTypeError",
    "DuplicateHandlerError",
    "EventBusError",
    "EventId",
    "EventNotFoundError",
    "EventRegistry",
    "EventSourceError",
    "EventStoreError",
    "EventTypeNotFoundError",
    "EventVersionError",
    "HandlerDispatchError",
    "HandlerSignatureError",
    "OptimisticLockError",
    "ProjectionError",
    "SerializationError",
    "SnapshotDeserializationError",
    "SnapshotError",
    "SnapshotNotFoundError",
    "SnapshotSchemaVersionError",
    "StreamId",
    "TenantContextNotSetError",
    "TenantContextResetError",
    "TenantId",
    "TenantMismatchError",
    "UnhandledEventError",
    "default_registry",
    "get_event_class",
    "get_event_class_or_none",
    "is_event_registered",
    "list_registered_events",
    "register_event",
]
